const stories = {
    happy: [
        { title: "The Butter Thief", text: "Young Krishna loved butter and would often steal it from the homes of Gokul. The villagers, annoyed yet amused, complained to Yashoda, who one day caught Krishna red-handed. When she scolded him, Krishna innocently smiled and said, “Mother, I only take what belongs to me. Love, joy, and kindness should be shared, just like butter!”", moral: "True happiness comes from sharing and spreading joy rather than hoarding possessions." },
        { title: "Krishna and Sudama", text: "Sudama, a poor Brahmin, was Krishna’s childhood friend. Years later, he visited Krishna in his palace, carrying only a handful of puffed rice as a gift. Krishna welcomed him warmly, treating him like a king. Without Sudama asking for anything, Krishna secretly blessed his friend with wealth and prosperity.", moral: " True happiness lies in friendship, love, and selfless giving, not in material wealth." },
        { title: " The Peacock’s Feather", text: "One day, a peacock approached Krishna, saddened by its inability to sing like the cuckoo. Krishna smiled, took a feather from the peacock’s head, and placed it on his own crown. “You are unique in your own way. Do not compare yourself to others, for each creation has its own beauty.”", moral: "Happiness comes when we embrace our uniqueness instead of comparing ourselves with others." },
        { title: " The Flute’s Surrender", text: "Krishna’s flute was his most beloved instrument because it was empty inside, allowing him to create divine music. When his friends asked why he loved the flute so much, Krishna replied, “It is because it lets go of its ego and allows me to fill it with my breath.”", moral: "Happiness is found in surrendering ego and allowing divine grace to flow through us." },
        { title: " The Govardhan Mountain", text: "When heavy rains poured over Vrindavan, the villagers panicked. Krishna lifted the mighty Govardhan mountain on his little finger and sheltered everyone. Later, he reminded them, “Nature’s balance and self-reliance bring happiness. Depend on your own efforts and faith rather than seeking external security.”", moral: " True happiness comes from faith in oneself and the divine rather than relying on external circumstances." }
    ],
    peace: [
        { title: "Krishna and the Angry Sage", text: "A sage once came to Krishna, furious about how people were treating him unfairly. Krishna smiled and gave him a bowl filled to the brim with oil. “Walk around the palace with this, but don’t spill a drop,” he instructed. The sage returned without spilling a drop. Krishna then asked, “Did you hear anyone insult you?” The sage realized that when he focused on his task, he ignored distractions.", moral: "Peace comes from focusing on our own path rather than reacting to external negativity." },
        { title: "The Peacock and the Crow", text: "A crow once complained to Krishna that it had no bright colors like the peacock. Krishna replied, “Do you know why the peacock dances? Because it is content with itself.” The crow, understanding this, stopped comparing itself to others and found peace in its own strengths.", moral: "Peace is found in self-acceptance and contentment rather than comparison." },
        { title: "The Kauravas’ Pride", text: "Before the Kurukshetra war, Krishna tried to negotiate peace between the Pandavas and Kauravas. Duryodhana, blinded by pride, refused. Krishna warned him, “Pride leads to destruction, and humility leads to peace.” But Duryodhana ignored him, leading to his downfall.", moral: "Peace is maintained when one lets go of arrogance and embraces humility." },
        { title: "The Serpent Kaliya", text: "The poisonous serpent Kaliya made the Yamuna River toxic, causing suffering to the people. Krishna danced on Kaliya’s hood and subdued him. Instead of killing him, Krishna told him to leave and never harm others again. Kaliya, humbled, left in peace.", moral: "Peace is achieved not by destruction but by transforming negativity into positivity." },
        { title: "The Lost Calf", text: "Once, Krishna and his friends were playing when a calf went missing. While everyone panicked, Krishna calmly observed, listened, and eventually found the calf drinking water by the river. His patience and awareness restored peace among his friends.", moral: "Peace comes from patience, observation, and trusting the flow of life." }
    ],
    anxiety: [
        { title: "Arjuna’s Doubt on the Battlefield", text: "As the Kurukshetra war began, Arjuna was overwhelmed with anxiety, fearing the consequences of battle. He dropped his bow, saying, “I cannot fight.” Krishna reassured him, explaining the eternal nature of the soul and the importance of duty. “Do your duty without attachment to results, and anxiety will disappear.”", moral: "Anxiety fades when we focus on action rather than worrying about outcomes." },
        { title: "Krishna and the Rope of Worry", text: "Yashoda once tried to tie little Krishna to a grinding stone as punishment for his mischief, but no matter how much rope she added, it was always a little short. She finally gave up, laughing. Krishna then let himself be tied. “See, Mother,” he said, “sometimes, when we stop trying so hard, things fall into place.”", moral: "Overthinking makes anxiety worse; letting go brings peace." },
        { title: " The Merchant’s Fear", text: " A merchant worried constantly about his wealth being stolen. He approached Krishna, who gave him a small pot of water. “Carry this around all day without spilling a drop,” Krishna said. The merchant focused on the pot so much that he forgot his worries. At the end of the day, Krishna smiled, “See how anxiety fades when the mind is occupied with purpose?”", moral: " Anxiety lessens when we have faith in something greater than ourselves." },
        { title: "The Child in the Storm", text: "One night, a fierce storm hit Vrindavan. The people panicked, but a small child slept peacefully under a tree. Krishna pointed at him and said, “Look at this child. He trusts that his parents will protect him. If we trust in the divine, why should we fear?”", moral: "Trust in divine protection during tough times." },
        { title: "The Crow and the Traveler", text: "A man traveling to Dwaraka worried about reaching safely. He saw a crow pecking at grains, flying away calmly even when strong winds blew. Krishna, watching, said, “The crow eats what it finds today, not worrying about tomorrow. Learn from it.”", moral: "Living in the present moment reduces anxiety about the future." }
    ],
    anger: [
        { title: "Krishna and Shishupala’s Hundred Mistakes", text: " Shishupala, Krishna’s cousin, hated him and insulted him repeatedly. Krishna patiently forgave him 100 times, as promised to Shishupala’s mother. But when Shishupala crossed the limit, Krishna used his Sudarshan Chakra to end his tyranny.", moral: "Patience can control anger, but allowing injustice indefinitely is also wrong." },
        { title: "The Hot Milk Incident", text: " Once, Yashoda was feeding baby Krishna when she noticed milk boiling over in the kitchen. She put Krishna down and rushed to save the milk. Angry at being left, Krishna broke the butter pots. Yashoda, instead of getting furious, lovingly tied him to a grinding stone, teaching discipline with affection.", moral: "Respond to anger with understanding, not more anger." },
        { title: "Krishna and the Farmer’s Patience", text: " A farmer’s field was destroyed in a storm. Furious, he cursed his fate and blamed Krishna. Krishna smiled and said, “Anger won’t bring back your crops. But patience will help you replant them.” Realizing this, the farmer let go of his anger and started anew.", moral: "Anger blinds us, while patience helps us rebuild." },
        { title: "Balarama’s Rage at Rukmi", text: "Rukmi, Rukmini’s brother, constantly insulted Krishna. During a dice game, he mocked Balarama, who became furious and wanted to kill him. Krishna calmed Balarama, saying, “A wise man does not let words control his emotions.” Instead of killing Rukmi, Balarama simply humiliated him.", moral: "Controlling anger makes you stronger, not weaker." },
        { title: "Narada’s Curse of the Yadavas", text: "Once, Krishna’s sons played a prank on Sage Narada, pretending one of them was a pregnant woman. Angered by their disrespect, Narada cursed them, leading to their downfall. Krishna accepted the curse without anger, knowing destiny must unfold.", moral: " Responding to anger with wisdom prevents unnecessary destruction." }

    ],
    sad: [
        { title: "Arjuna’s Sorrow on the Battlefield", text: " Before the Kurukshetra war, Arjuna was filled with sorrow, thinking about fighting his own family. He told Krishna, “How can I fight my own loved ones?” Krishna consoled him, teaching the Bhagavad Gita: “The soul is eternal. Do your duty without attachment, and sorrow will leave you.”", moral: " Sadness fades when we accept life’s purpose and act with wisdom." },
        { title: " Radha’s Longing for Krishna", text: "After Krishna left Vrindavan, Radha and the gopis were heartbroken. But Radha understood that Krishna was always with them in spirit. Instead of being sad, she immersed herself in devotion, feeling his presence everywhere.", moral: "True love and connection are beyond physical presence; find joy in the eternal bond." },
        { title: "Krishna and the Weeping Child", text: "A little boy cried when his clay toy broke. Krishna smiled and made a new one for him, saying, “Nothing is lost forever; new things come in their place.” The boy laughed, forgetting his sorrow.", moral: "Sorrow is universal, but sharing and understanding help heal it." },
        { title: "The Broken Flute", text: "Krishna’s favorite flute broke one day. Instead of being sad, he said, “This flute has served its purpose. Now it will return to nature.” He made a new flute and continued playing beautiful melodies.", moral: "Everything has a time; instead of mourning the past, embrace new beginnings." },
        { title: " The Widow’s Sorrow", text: " A woman lost her husband and lived in grief. Krishna told her to find a household where no one had lost a loved one. She searched but found that every home had experienced loss. Realizing she was not alone, she overcame her sorrow.", moral: "Sorrow is universal, but sharing and understanding help heal it." }

    ],
    protection: [
        { title: "Krishna Protects Draupadi’s Honor", text: "During the Kauravas' attempt to dishonor Draupadi by disrobing her in the royal court, she prayed to Krishna for help. As Dushasana pulled at her saree, Krishna miraculously provided an unending stream of cloth, preventing her from being humiliated.", moral: "Faith in God brings divine protection in times of crisis." },
        { title: "Krishna and the Govardhan Hill", text: "When Lord Indra sent torrential rains to punish the people of Vrindavan, Krishna lifted the Govardhan Hill with his little finger and provided shelter for everyone. After seven days, Indra realized Krishna’s divinity and stopped the storm.", moral: "True leadership means protecting others, even in the face of great challenges." },
        { title: "Krishna Saves the Devotee’s Boat", text: "A poor devotee was once crossing a river in a boat, chanting Krishna’s name. A fierce storm arose, and the boat was about to sink. Remembering Krishna, he surrendered to Him. Miraculously, the storm calmed, and he reached the shore safely.", moral: "Sincere devotion and surrender bring divine rescue." },
        { title: "Krishna Rescues Gajendra, the Elephant", text: "The elephant king, Gajendra, was caught by a crocodile in a lake. Despite his immense strength, he couldn’t escape. He called out to Lord Vishnu (Krishna), who appeared instantly and rescued him by slaying the crocodile.", moral: "In moments of helplessness, seeking divine help brings ultimate salvation." },
        { title: "Krishna Protects Arjuna in the Battlefield", text: "During the Mahabharata war, Krishna served as Arjuna’s charioteer. When Karna aimed a deadly arrow at Arjuna, Krishna subtly pressed the chariot down into the earth, causing the arrow to miss his head and only hit his crown.", moral: "God protects those who fight for righteousness and follow the path of Dharma." }

    ],
    laziness: [
        { title: "The Lazy Disciple and Krishna’s Advice", text: "A disciple of Krishna was always postponing his prayers, saying, 'I will do it tomorrow' One day, Krishna appeared in his dream and told him, 'What if death comes tomorrow? Will you postpone life too?' The disciple woke up and changed his ways.", moral: "Never delay important duties, as time waits for no one." },
        { title: "The Farmer Who Waited for Krishna", text: "A lazy farmer prayed to Krishna for a good harvest but never worked on his land. When his crops failed, he blamed Krishna. Krishna appeared and said, 'Even I cannot help those who do nothing for themselves.'", moral: "God helps those who help themselves." },
        { title: " The Cowherd Who Slept Through the Storm", text: "A cowherd in Vrindavan was too lazy to bring his cows into the shed before a storm. He thought, 'Krishna protects everything, so why should I bother?' The next morning, he found his cows missing. Krishna told him, 'I give strength to the hardworking, not excuses for the lazy.'", moral: "Faith is not an excuse for laziness—effort is necessary." },
        { title: "The Boy Who Missed Krishna’s Visit", text: "A young devotee was excited to meet Krishna but was too lazy to wake up early. When Krishna finally visited his village, the boy was still asleep. By the time he woke up, Krishna had already left.", moral: "Opportunities are lost by those who are lazy and unprepared." },
        { title: "The Lazy Student and the Bhagavad Gita", text: "A student avoided studying, thinking he could pray to Krishna for knowledge instead. When the exam came, he failed. Krishna appeared in his dream and said, 'Knowledge comes from effort, not just prayers.'", moral: "Success requires hard work, not just wishes and prayers." }

    ],
    loneliness: [
        { title: " Krishna and the Lonely Devotee", text: "A poor man in Vrindavan felt lonely and abandoned. He prayed to Krishna, saying, 'No one is with me.' That night, Krishna appeared in his dream and said, 'I am always with you. Look into your heart, and you will find me.' The man woke up feeling peaceful, never lonely again.", moral: "You are never truly alone—God resides within you." },
        { title: "Sudama’s Loneliness Ends with Friendship", text: "Sudama, Krishna’s childhood friend, lived in poverty and loneliness. He hesitated to visit Krishna, fearing rejection. But when he finally went, Krishna embraced him with love and ended his suffering.", moral: "True friends never forget you, even in difficult times." },
        { title: "The Gopis' Longing for Krishna", text: "When Krishna left Vrindavan for Mathura, the Gopis felt deep loneliness. They found solace by remembering his teachings and playing his flute tunes. Their devotion made them feel Krishna’s presence even in his absence.", moral: " Love and devotion can fill the void of loneliness." },
        { title: "Arjuna’s Loneliness Before the War", text: "Before the Kurukshetra war, Arjuna felt lost and alone, unsure of his duty. Krishna gave him the wisdom of the Bhagavad Gita, teaching him that he was never alone—his dharma and Krishna’s guidance were always with him.", moral: "Purpose and wisdom can overcome loneliness." },
        { title: "The Hermit Who Found Krishna in Silence", text: "A hermit lived alone in the forest, seeking Krishna but feeling disconnected. One day, he heard Krishna’s voice in the wind, the river, and the birds. He realized he was never truly alone—Krishna was everywhere.", moral: "Loneliness fades when you see the divine presence in everything." }

    ]
};

document.querySelectorAll(".mood-btn").forEach(button => {
    button.addEventListener("click", function() {
        const mood = this.getAttribute("data-mood");
        const moodStories = stories[mood];
        const randomStory = moodStories[Math.floor(Math.random() * moodStories.length)];

        document.getElementById("story-title").textContent = randomStory.title;
        document.getElementById("story-text").textContent = randomStory.text;
        document.getElementById("story-moral").textContent = "Moral: " + randomStory.moral;
    });
});
